### ISSUE TITLE
Safenet Protect Server HSM Simulator and Edit Attributes

### ISSUE THREAD

**Issue by mikejhathaway** [jariq/Pkcs11Admin#33]
Hi,

When trying to use PKCS11Admin with a Safenet Protect Server HSM Simulator and Edit Attributes, PKCS11Admin generates an exception:

Unable to convert bytes to Ulnt32

Here is the details

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Unable to convert bytes to UInt32
   at Net.Pkcs11Interop.Common.ConvertUtils.UInt32FromBytes(Byte[] value)
   at Net.Pkcs11Interop.HighLevelAPI41.ObjectAttribute.GetValueAsUlong()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3468.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Pkcs11Admin.WinForms
    Assembly Version: 0.5.0.0
    Win32 Version: 0.5.0
    CodeBase: file:///D:/SW/Tools/Pkcs11Admin-0.5.0/Pkcs11Admin-0.5.0/Pkcs11Admin-x64.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3451.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Pkcs11Admin
    Assembly Version: 0.5.0.0
    Win32 Version: 0.5.0
    CodeBase: file:///D:/SW/Tools/Pkcs11Admin-0.5.0/Pkcs11Admin-0.5.0/Pkcs11Admin.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3570.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Pkcs11Interop
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///D:/SW/Tools/Pkcs11Admin-0.5.0/Pkcs11Admin-0.5.0/Pkcs11Interop.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by jariq** [comment]
I'm sorry I didn't reply in time @mikejhathaway. Do you still want to discuss this issue after such a long time or can it be closed?
